### PR TITLE
WIP: Fixing types, defining new status types, making sure all functio…

### PR DESCRIPTION
**Pull request by sriramster**
…ns return status, converting char * to with const pointers (paradox)

Signed-off-by: Sriram Raghunathan <sriram.max@gmail.com>

### CODE REVIEW

**Comment by sriramster** [comment]
Hello, I'm trying to restructure and re-write a few pieces of code for optimization and readability. Please consider this patch in the series. I'd be glad to work more on this, if the approach taken here is something that interests you. Thank you.

**Comment by sg777** [comment]
I see there are many instances this function `bet_msg_dealer_with_response_id` is getting called, changing the prototype of it will have impact on those calls. And I see no changes to the bet.c and cashier.c and .h files where this function is called.

**Comment by sriramster** [comment]
Hi, @sg777 , 

The bet_msg_dealer_with_response_id change was needed to get a uniform return type for network related APIs and to save back the status information we are using an arugment passed onto the function. Though the change could have ripple effect, it seems necesary to bring up clarity and readability. Please advice.

**Comment by sg777** [comment]
Hi @sriramster, Got your point, this morning going through the changes, I see the change in return values in value and function prototypes I see I need to make lots of changes in other parts of the repo.

**Comment by sg777** [comment]
Hi @sriramster, 

I'm closing this pull request, once after pulling latest changes can you please raise new PR.

-SG

**Pull request closed without merging**
